### PR TITLE
ITM-706:  Update SoarTech DRE KDMA scores to add scalar value

### PR DESCRIPTION
**Pull request by nextcen-dgemoets**
SoarTech has pushed out a branch (`exp/scalar-kdma`) that contains the DRE scenarios and now returns scalar KDMA values along with session alignment.  This is hosted on AWS so you don't need to change anything in your environment.

This script gets probe responses from text scenario, sim, and adm output, sends the responses to the modified SoarTech server, and updates the database with the scalar kdma value, while leaving the existing data intact.

There's also an option to dump csv-like output for text and sim kdma data, which was needed to get these values for analysis prior to them being present in the dashboard.  It is kept in the code for historical reasons.

Note there are a few cases where not all probe responses were collected by the sim, so the SoarTech endpoint won't return alignment and kdma values.  In these cases, I manually averaged the kdma values for the probes that did have responses, and that value to the DB.

To test, run the script and ensure that the kdma `value` appears with the rest of the KDMA information in each of the three affected DB tables.

This ticket will be followed by [ITM-742](https://nextcentury.atlassian.net/browse/ITM-742), which will include the dashboard changes to use these new data.

[ITM-742]: https://nextcentury.atlassian.net/browse/ITM-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
LGTM!

```
(venv) ple@ple-Virtual-Machine:~/ITM/itm-ingest$ python update_dre_kdmas.py 
Processing SoarTech Text KDMAs...
...
PID=20249202, KDMA = QualityOfLife, value = 0.5833333333333334
PID=20249202, KDMA = PerceivedQuantityOfLivesSaved, value = 0.31666666666666665
...
```

In Mongo after run:
userScenarioResults:
```
    kdmas: {
      computed_kdma_profile: [
        {
          kdma: 'QualityOfLife',
          value: 0.5833333333333334,
...
    kdmas: {
      computed_kdma_profile: [
        {
          kdma: 'PerceivedQuantityOfLivesSaved',
          value: 0.31666666666666665,
```
humanSimulator (only QOL):
```
      kdmas: {
        computed_kdma_profile: [
          {
            kdma: 'QualityOfLife',
            value: 0.5833333333333334,

```

**Review by kaitlyn-sharo — APPROVED** [review]
Looks good, and works for me. Just curious why this isn't in the scripts section to autorun?

**Comment by brianpippin** [comment]
> Looks good, and works for me. Just curious why this isn't in the scripts section to autorun?

I was going to note this should be in the scripts section to run and update the db version like our usual script pattern.  Otherwise it is good.

**Comment by nextcen-dgemoets** [comment]
> > Looks good, and works for me. Just curious why this isn't in the scripts section to autorun?
> 
> I was going to note this should be in the scripts section to run and update the db version like our usual script pattern. Otherwise it is good.

Done; thanks.

**Comment by nextcen-dgemoets** [comment]
Please standby on this one.  Working to get it to work properly with deployment script setup.

**Comment by nextcen-dgemoets** [comment]
This should probably be re-run by reviewers so they can update their DB version.  Or at least, the next time they deploy, it will re-run this script.

**Review by dereknop — APPROVED** [review]
Found an issue with my deployment script. Will put out pr shortly. Instead of current method of searching, will look for `main` in these scripts. I will update the readme accordingly

**Pull request merged**
