### PR TITLE
ITM-459 data for eval drop downs

### PR DESCRIPTION
**Pull request by phile-caci**
Corresponding dashboard ticket: [dashboard ticket](https://github.com/NextCenturyCorporation/itm-evaluation-dashboard/pull/80l)

This adds evalName and evalNumber to surveyResults and userScenarioResults

This isn't quite idempotent, if this is run some time in the future it may not be correct.
```
db.surveyResults.updateMany({"evalName": null}, { $set: { "evalNumber": 3 } }) 
db.surveyResults.updateMany({"evalName": null}, { $set: { "evalName": "Metrics Evaluation" } }) 
db.userScenarioResults.updateMany({"evalName": null}, { $set: { "evalNumber": 3 } }) 
db.userScenarioResults.updateMany({"evalName": null}, { $set: { "evalName": "Metrics Evaluation" } }) 
```

Also add an evaluationIDS table

```
db.createCollection("evaluationIDS")  
db.evaluationIDS.insertOne({  
  "evalNumber": 1,  
  "evalName": "MVP",  
  "showMainPage": false})  
db.evaluationIDS.insertOne({  
  "evalNumber": 2,  
  "evalName": "September Milestone",  
  "showMainPage": false})  
db.evaluationIDS.insertOne({  
  "evalNumber": 3,  
  "evalName": "Metrics Evaluation",  
  "showMainPage": true})  
db.evaluationIDS.insertOne({  
  "evalNumber": 4,  
  "evalName": "Dry Run Evaluation",  
  "showMainPage": false})  
```

### CODE REVIEW

**Review by brianpippin — COMMENTED** [review]
Phi - I tried to run this and I don't think the new script file was added to the remote branch.  I don't see the 0_1_9 file.

**Comment by phile-caci** [comment]
> Phi - I tried to run this and I don't think the new script file was added to the remote branch. I don't see the 0_1_9 file.

Opps... it's added now!

**Review by brianpippin — APPROVED** [review]
Appears to be a potential merge issue, but the script worked.  Also you or Derek will need to update your reviews at some point because both of your reviews have a db_version of 0.1.9

**Comment by phile-caci** [comment]
> Appears to be a potential merge issue, but the script worked. Also you or Derek will need to update your reviews at some point because both of your reviews have a db_version of 0.1.9

I'll update mine to 0.1.10

**Comment by brianpippin** [comment]
> > Appears to be a potential merge issue, but the script worked. Also you or Derek will need to update your reviews at some point because both of your reviews have a db_version of 0.1.9
> 
> I'll update mine to 0.1.10

This is merging first so @dereknop should update his to 0.1.10

**Pull request merged**
