### PR TITLE
Itm 550

### PR DESCRIPTION
**Pull request by dereknop**
[ITM-550](https://nextcentury.atlassian.net/jira/software/projects/ITM/boards/116?assignee=60ba425da547eb00686ee0ce&selectedIssue=ITM-550)

Small fix to remove patients marked as unseen from the UI. I was going to bundle this with splitting Adept probes but that is proving more troublesome. 

The script should now replace the current `textBasedImages` and `textBasedConfig` collections so there is no need to manually delete any collections before running `python3 deployment_script.py`

[ITM-550]: https://nextcentury.atlassian.net/browse/ITM-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
No issues running, also reran multiple times after modifying the deployment script `if(check_version(mongoDB)):` line to allow the these lines to run again:

```
        generate_textbased_configs()
        add_pictures()
        update_db_version(mongoDB)
```

Just a note, some collections have `evalName` and `evalNumber` to id the eval.  Any need for to standardize it for the textBased scenarios?

**Comment by dereknop** [comment]
> Just a note, some collections have `evalName` and `evalNumber` to id the eval. Any need for us to standardize it for the textBased scenarios?

With the way the dashboard is set up right now, that isn't necessary. But thanks for pointing this out. I can add this later on if needed.

**Comment by nextcen-dgemoets** [comment]
In `DryRunEval-MJ5-eval` Scene 3 ("You go partway around the building, and a US soldier tells you more about the situation"), why  isn't the US soldier shown?  He isn't unseen.

**Comment by dereknop** [comment]
> In `DryRunEval-MJ5-eval` Scene 3 ("You go partway around the building, and a US soldier tells you more about the situation"), why isn't the US soldier shown? He isn't unseen.

Only characters that have an action in the action mapping that corresponds to them are shown. I'll ask Adept about this specific case tomorrow.

**Review by kaitlyn-sharo — APPROVED** [review]

**Pull request merged**
