### PR TITLE
Itm 714 rerun st

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Reruns the soartech session alignment.
Removes adms that we are not using.
Renames long-named kitware adms to dre convention.

To test, use the latest database (from Phi or me). Check that the ST alignment scores change after running and that you end with 384 adm entries for evalNumber: 5

### CODE REVIEW

**Comment by phile-caci** [comment]
@kaitlyn-sharo , The scores updated as expected, but I seem to have some stragglers after my run (with the ADM Name Update), did you get this too?  If not, I'll reset and rerun.
```
dashboard> db.test.distinct("history.parameters.adm_name", {"evalNumber": 5})
[
  'ALIGN-ADM-ComparativeRegression-ICL-Template',
  'ALIGN-ADM-ComparativeRegression-Llama-3.2-3B-Instruct-SoarTech-MatchingChars__5f94293d-a834-4ae7-b3c3-d820a377a6db',
  'ALIGN-ADM-ComparativeRegression-Mistral-7B-Instruct-v0.3-ADEPT__0fb8644c-086f-4e56-89b7-da65f191530e',
  'ALIGN-ADM-OutlinesBaseline',
  'ALIGN-ADM-OutlinesBaseline__07b34c32-7f75-488d-9ce7-ad31c638fd0b',
  'ALIGN-ADM-OutlinesBaseline__9a0c9e90-3140-40fb-8fe6-36f9508ccd36',
  'TAD-aligned',
  'TAD-severity-baseline'
]
```
```
dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-OutlinesBaseline__07b34c32-7f75-488d-9ce7-ad31c638fd0b"})
1
dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-OutlinesBaseline__9a0c9e90-3140-40fb-8fe6-36f9508ccd36"})
1
dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-ComparativeRegression-Mistral-7B-Instruct-v0.3-ADEPT__0fb8644c-086f-4e56-89b7-da65f191530e"})
1
dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-ComparativeRegression-Llama-3.2-3B-Instruct-SoarTech-MatchingChars__5f94293d-a834-4ae7-b3c3-d820a377a6db"})
1
```

**Comment by kaitlyn-sharo** [comment]
> @kaitlyn-sharo , The scores updated as expected, but I seem to have some stragglers after my run (with the ADM Name Update), did you get this too? If not, I'll reset and rerun.
> 
> ```
> dashboard> db.test.distinct("history.parameters.adm_name", {"evalNumber": 5})
> [
>   'ALIGN-ADM-ComparativeRegression-ICL-Template',
>   'ALIGN-ADM-ComparativeRegression-Llama-3.2-3B-Instruct-SoarTech-MatchingChars__5f94293d-a834-4ae7-b3c3-d820a377a6db',
>   'ALIGN-ADM-ComparativeRegression-Mistral-7B-Instruct-v0.3-ADEPT__0fb8644c-086f-4e56-89b7-da65f191530e',
>   'ALIGN-ADM-OutlinesBaseline',
>   'ALIGN-ADM-OutlinesBaseline__07b34c32-7f75-488d-9ce7-ad31c638fd0b',
>   'ALIGN-ADM-OutlinesBaseline__9a0c9e90-3140-40fb-8fe6-36f9508ccd36',
>   'TAD-aligned',
>   'TAD-severity-baseline'
> ]
> ```
> 
> ```
> dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-OutlinesBaseline__07b34c32-7f75-488d-9ce7-ad31c638fd0b"})
> 1
> dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-OutlinesBaseline__9a0c9e90-3140-40fb-8fe6-36f9508ccd36"})
> 1
> dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-ComparativeRegression-Mistral-7B-Instruct-v0.3-ADEPT__0fb8644c-086f-4e56-89b7-da65f191530e"})
> 1
> dashboard> db.test.count({"history.parameters.adm_name":"ALIGN-ADM-ComparativeRegression-Llama-3.2-3B-Instruct-SoarTech-MatchingChars__5f94293d-a834-4ae7-b3c3-d820a377a6db"})
> 1
> ```

That _should_ be fixed in the latest push.

**Review by phile-caci — APPROVED** [review]
My bad, didn't pull latest, LGTM!

1. Compared scores from Dev to Prod, looks like they changed
2. Unused ADM's removed
(After running script)
```
dashboard> db.test.distinct("history.parameters.adm_name", {"evalNumber": 5})
[
  'ALIGN-ADM-ComparativeRegression-ICL-Template',
  'ALIGN-ADM-OutlinesBaseline',
  'TAD-aligned',
  'TAD-severity-baseline'
]

```
3. Shorter ADM names where in the UI

**Review by nextcen-dgemoets — APPROVED** [review]
1. Compared scores from Dev to Prod, looks like they changed (and always higher alignment from what I could see).
2. Unused ADM's removed
```
dashboard> db.test.distinct("history.parameters.adm_name", {"evalNumber": 5})
[
  'ALIGN-ADM-ComparativeRegression-ICL-Template',
  'ALIGN-ADM-OutlinesBaseline',
  'TAD-aligned',
  'TAD-severity-baseline'
]

```
4. Shorter ADM names were in the UI.

The only tiny suggestion I'd add is to add some intermediate logging (prints) in a script like _0_3_6.  I thought maybe something was hung, but then it finally finished.  There's not always a good/useful place to add such logging, but sometimes you can e.g., in each iteration of a loop.

**Comment by kaitlyn-sharo** [comment]
> 1. Compared scores from Dev to Prod, looks like they changed (and always higher alignment from what I could see).
> 2. Unused ADM's removed
> 
> ```
> dashboard> db.test.distinct("history.parameters.adm_name", {"evalNumber": 5})
> [
>   'ALIGN-ADM-ComparativeRegression-ICL-Template',
>   'ALIGN-ADM-OutlinesBaseline',
>   'TAD-aligned',
>   'TAD-severity-baseline'
> ]
> ```
> 
> 4. Shorter ADM names were in the UI.
> 
> The only tiny suggestion I'd add is to add some intermediate logging (prints) in a script like _0_3_6. I thought maybe something was hung, but then it finally finished. There's not always a good/useful place to add such logging, but sometimes you can e.g., in each iteration of a loop.

Ooh I've used this really cool python library before that shows a progress bar, and since we know we're expecting 384 adms, I could totally use that. I will see if I get a chance to add it later today, otherwise, since that feature addition is low priority, I will just merge it

**Review by brianpippin — APPROVED** [review]
Both Kitware and Parallax confirm the scores are correct.

**Pull request merged**
