### PR TITLE
remove dup, update plog counts

### PR DESCRIPTION
**Pull request by dereknop**
Removes an incomplete survey that was causing issues (202411353) there is a complete one that it will use now instead. Also updates the sim, survey, and text entry counts in the participant log. 

`python deployment_script.py`

### CODE REVIEW

**Comment by kaitlyn-sharo** [comment]
Unfortunately, for this to fix the 353 problem, after it is run, the weekly script will also have to be run

**Review by phile-caci — APPROVED** [review]
No issues running on my end,

Hopefully this looks like right:
```
dashboard> db.participantLog.find({"ParticipantID": 202411353})
[
  {
    _id: ObjectId('6762df75ccce96634bd20b7b'),
    'Text-1': 'ST-2',
    'Text-2': 'AD-3',
    'Sim-1': 'ST-3',
    'Sim-2': 'AD-1',
    'Del-1': 'ST-1',
    'Del-2': 'AD-2',
    ADMOrder: 2,
    ParticipantID: 202411353,
    Type: 'emailParticipant',
    claimed: true,
    simEntryCount: 4,
    surveyEntryCount: 1,
    textEntryCount: 5,
    hashedEmail: '$2a$10$j0Bpq6e1b0556pu935uBduqU0h6GhLiVoCYVLe.E.GDMQWjEmT4.S'
  }
]
das
```

**Review by kaitlyn-sharo — COMMENTED** [review]
Ran this, ran weekly script, and 353 is now populating alignment in rq 1/3/4!

**Review by kaitlyn-sharo — CHANGES_REQUESTED** [review]
survey count needs to get Participant ID Page.questions.Participant ID.response

**Review by kaitlyn-sharo — APPROVED** [review]
derek's always breaking my code

**Review by nextcen-dgemoets — APPROVED** [review]
Ran this, ran weekly script, and 353 is now populating alignment in rq 1/3/4.  Wanted to see if it caused the DRE toggle problem, but that was resolved while the weekly script ran.

**Pull request merged**
