### PR TITLE
Itm 524

### PR DESCRIPTION
**Pull request by dereknop**
[ITM 524](https://nextcentury.atlassian.net/jira/software/projects/ITM/boards/116?assignee=60ba425da547eb00686ee0ce&selectedIssue=ITM-524)
To test get yourself into the ingest venv and then run:

`python deployment_script.py`

You should see console prints noting that yaml files have been processed and uploaded. These are the scenario yamls being converted to json configs for the dashboard. Next, see the [dashboard PR](https://github.com/NextCenturyCorporation/itm-evaluation-dashboard/compare/ITM-501?expand=1)

### CODE REVIEW

**Review by nextcen-dgemoets — COMMENTED** [review]
Worked like a charm!

But what are `desert.yaml` and other similarly-named files?  Are these the soartech MRE scenarios?  Why aren't they named e.g., `metrics-soartech-eval-desert.yaml` like the adept files?  And does it matter?

**Comment by dereknop** [comment]
> But what are `desert.yaml` and other similarly-named files? Are these the soartech MRE scenarios? Why aren't they named e.g., `metrics-soartech-eval-desert.yaml` like the adept files? And does it matter?

https://github.com/ITM-Soartech/ta1-server-mvp/tree/main/ta1_server/data/scenarios/current

They are the SoarTech MRE files. I didn't bother changing their naming convention as I just downloaded them straight from their GitHub. Although I probably will change that for clarity

**Review by kaitlyn-sharo — APPROVED** [review]

**Review by kaitlyn-sharo — APPROVED** [review]
The script seems to work and makes sense. Have not tested the dashboard yet

**Review by phile-caci — APPROVED** [review]
Didn't see any issues with the latest push.  Looks good on my end.

Images are showing up:
image

Ran scripts on a clean mongo, data came up on the ui (http://localhost:3000/review-text-based)
```
(venv) ple@ple-Virtual-Machine:~/ITM/itm-ingest$ python3.10 deployment_script.py
New db version, execute scripts
Processed and uploaded: metrics-adept-eval-desert.yaml
Processed and uploaded: metrics-adept-eval-submarine.yaml
Processed and uploaded: metrics-adept-eval-jungle.yaml
Processed and uploaded: urban.yaml
Processed and uploaded: submarine.yaml
Processed and uploaded: jungle.yaml
Processed and uploaded: metrics-adept-eval-urban.yaml
Processed and uploaded: desert.yaml
Processed and uploaded: dryrun-soartech-eval-qol2.yaml
Processed and uploaded: dryrun-soartech-eval-vol3.yaml
Processed and uploaded: dryrun-adept-eval-MJ4.yaml
Processed and uploaded: dryrun-adept-eval-MJ2.yaml
Processed and uploaded: dryrun-soartech-eval-vol2.yaml
Processed and uploaded: dryrun-soartech-eval-vol1.yaml
Processed and uploaded: dryrun-soartech-eval-qol3.yaml
Processed and uploaded: dryrun-adept-eval-MJ5.yaml
Processed and uploaded: dryrun-soartech-eval-qol1.yaml
Uploaded o.png to MongoDB with casualtyId: casualty_o, scenarioId: vol-dre-3-eval
Uploaded n.png to MongoDB with casualtyId: casualty_n, scenarioId: vol-dre-3-eval
Uploaded u.png to MongoDB with casualtyId: casualty_u, scenarioId: vol-dre-3-eval
Uploaded p.png to MongoDB with casualtyId: casualty_p, scenarioId: vol-dre-3-eval
Uploaded v.png to MongoDB with casualtyId: casualty_v, scenarioId: vol-dre-3-eval
Uploaded w.png to MongoDB with casualtyId: casualty_w, scenarioId: vol-dre-3-eval
Uploaded g.png to MongoDB with casualtyId: casualty_g, scenarioId: vol-dre-3-eval
Uploaded y.png to MongoDB with casualtyId: casualty_y, scenarioId: vol-dre-3-eval
Uploaded c.png to MongoDB with casualtyId: casualty_c, scenarioId: vol-dre-3-eval
Uploaded b.png to MongoDB with casualtyId: casualty_b, scenarioId: vol-dre-3-eval
Uploaded x.png to MongoDB with casualtyId: casualty_x, scenarioId: vol-dre-3-eval
Uploaded h.png to MongoDB with casualtyId: casualty_h, scenarioId: vol-dre-3-eval
Uploaded o.png to MongoDB with casualtyId: casualty_o, scenarioId: qol-dre-3-eval
Uploaded n.png to MongoDB with casualtyId: casualty_n, scenarioId: qol-dre-3-eval
Uploaded u.png to MongoDB with casualtyId: casualty_u, scenarioId: qol-dre-3-eval
Uploaded a.png to MongoDB with casualtyId: casualty_a, scenarioId: qol-dre-3-eval
Uploaded w.png to MongoDB with casualtyId: casualty_w, scenarioId: qol-dre-3-eval
Uploaded m.png to MongoDB with casualtyId: casualty_m, scenarioId: qol-dre-3-eval
Uploaded z.png to MongoDB with casualtyId: casualty_z, scenarioId: qol-dre-3-eval
Uploaded g.png to MongoDB with casualtyId: casualty_g, scenarioId: qol-dre-3-eval
Uploaded y.png to MongoDB with casualtyId: casualty_y, scenarioId: qol-dre-3-eval
Uploaded l.png to MongoDB with casualtyId: casualty_l, scenarioId: qol-dre-3-eval
Uploaded x.png to MongoDB with casualtyId: casualty_x, scenarioId: qol-dre-3-eval
Uploaded h.png to MongoDB with casualtyId: casualty_h, scenarioId: qol-dre-3-eval
Uploaded victim.png to MongoDB with casualtyId: victim, scenarioId: DryRunEval-MJ2-eval
Uploaded US military member.png to MongoDB with casualtyId: US military member, scenarioId: DryRunEval-MJ2-eval
Uploaded translator.png to MongoDB with casualtyId: translator, scenarioId: DryRunEval-MJ2-eval
Uploaded shooter.png to MongoDB with casualtyId: shooter, scenarioId: DryRunEval-MJ2-eval
Uploaded o.png to MongoDB with casualtyId: casualty_o, scenarioId: qol-dre-2-eval
Uploaded n.png to MongoDB with casualtyId: casualty_n, scenarioId: qol-dre-2-eval
Uploaded u.png to MongoDB with casualtyId: casualty_u, scenarioId: qol-dre-2-eval
Uploaded a.png to MongoDB with casualtyId: casualty_a, scenarioId: qol-dre-2-eval
Uploaded w.png to MongoDB with casualtyId: casualty_w, scenarioId: qol-dre-2-eval
Uploaded m.png to MongoDB with casualtyId: casualty_m, scenarioId: qol-dre-2-eval
Uploaded z.png to MongoDB with casualtyId: casualty_z, scenarioId: qol-dre-2-eval
Uploaded g.png to MongoDB with casualtyId: casualty_g, scenarioId: qol-dre-2-eval
Uploaded y.png to MongoDB with casualtyId: casualty_y, scenarioId: qol-dre-2-eval
Uploaded l.png to MongoDB with casualtyId: casualty_l, scenarioId: qol-dre-2-eval
Uploaded x.png to MongoDB with casualtyId: casualty_x, scenarioId: qol-dre-2-eval
Uploaded h.png to MongoDB with casualtyId: casualty_h, scenarioId: qol-dre-2-eval
Uploaded us_soldier.png to MongoDB with casualtyId: us_soldier, scenarioId: DryRunEval-MJ5-eval
Uploaded Springer.png to MongoDB with casualtyId: Springer, scenarioId: DryRunEval-MJ5-eval
Uploaded Upton.png to MongoDB with casualtyId: Upton, scenarioId: DryRunEval-MJ5-eval
Uploaded insurgent.png to MongoDB with casualtyId: insurgent, scenarioId: DryRunEval-MJ5-eval
Uploaded Kicker.png to MongoDB with casualtyId: Kicker, scenarioId: DryRunEval-MJ4-eval
Uploaded Passerby.png to MongoDB with casualtyId: Passerby, scenarioId: DryRunEval-MJ4-eval
Uploaded US Soldier.png to MongoDB with casualtyId: US Soldier, scenarioId: DryRunEval-MJ4-eval
Uploaded o.png to MongoDB with casualtyId: casualty_o, scenarioId: vol-dre-2-eval
Uploaded n.png to MongoDB with casualtyId: casualty_n, scenarioId: vol-dre-2-eval
Uploaded u.png to MongoDB with casualtyId: casualty_u, scenarioId: vol-dre-2-eval
Uploaded p.png to MongoDB with casualtyId: casualty_p, scenarioId: vol-dre-2-eval
Uploaded v.png to MongoDB with casualtyId: casualty_v, scenarioId: vol-dre-2-eval
Uploaded w.png to MongoDB with casualtyId: casualty_w, scenarioId: vol-dre-2-eval
Uploaded g.png to MongoDB with casualtyId: casualty_g, scenarioId: vol-dre-2-eval
Uploaded y.png to MongoDB with casualtyId: casualty_y, scenarioId: vol-dre-2-eval
Uploaded c.png to MongoDB with casualtyId: casualty_c, scenarioId: vol-dre-2-eval
Uploaded b.png to MongoDB with casualtyId: casualty_b, scenarioId: vol-dre-2-eval
Uploaded x.png to MongoDB with casualtyId: casualty_x, scenarioId: vol-dre-2-eval
Uploaded h.png to MongoDB with casualtyId: casualty_h, scenarioId: vol-dre-2-eval
Uploaded o.png to MongoDB with casualtyId: casualty_o, scenarioId: vol-dre-1-eval
Uploaded n.png to MongoDB with casualtyId: casualty_n, scenarioId: vol-dre-1-eval
Uploaded u.png to MongoDB with casualtyId: casualty_u, scenarioId: vol-dre-1-eval
Uploaded p.png to MongoDB with casualtyId: casualty_p, scenarioId: vol-dre-1-eval
Uploaded v.png to MongoDB with casualtyId: casualty_v, scenarioId: vol-dre-1-eval
Uploaded w.png to MongoDB with casualtyId: casualty_w, scenarioId: vol-dre-1-eval
Uploaded g.png to MongoDB with casualtyId: casualty_g, scenarioId: vol-dre-1-eval
Uploaded y.png to MongoDB with casualtyId: casualty_y, scenarioId: vol-dre-1-eval
Uploaded c.png to MongoDB with casualtyId: casualty_c, scenarioId: vol-dre-1-eval
Uploaded b.png to MongoDB with casualtyId: casualty_b, scenarioId: vol-dre-1-eval
Uploaded x.png to MongoDB with casualtyId: casualty_x, scenarioId: vol-dre-1-eval
Uploaded h.png to MongoDB with casualtyId: casualty_h, scenarioId: vol-dre-1-eval
Uploaded o.png to MongoDB with casualtyId: casualty_o, scenarioId: qol-dre-1-eval
Uploaded n.png to MongoDB with casualtyId: casualty_n, scenarioId: qol-dre-1-eval
Uploaded u.png to MongoDB with casualtyId: casualty_u, scenarioId: qol-dre-1-eval
Uploaded a.png to MongoDB with casualtyId: casualty_a, scenarioId: qol-dre-1-eval
Uploaded w.png to MongoDB with casualtyId: casualty_w, scenarioId: qol-dre-1-eval
Uploaded m.png to MongoDB with casualtyId: casualty_m, scenarioId: qol-dre-1-eval
Uploaded z.png to MongoDB with casualtyId: casualty_z, scenarioId: qol-dre-1-eval
Uploaded g.png to MongoDB with casualtyId: casualty_g, scenarioId: qol-dre-1-eval
Uploaded y.png to MongoDB with casualtyId: casualty_y, scenarioId: qol-dre-1-eval
Uploaded l.png to MongoDB with casualtyId: casualty_l, scenarioId: qol-dre-1-eval
Uploaded x.png to MongoDB with casualtyId: casualty_x, scenarioId: qol-dre-1-eval
Uploaded h.png to MongoDB with casualtyId: casualty_h, scenarioId: qol-dre-1-eval
```

**Pull request merged**
