### PR TITLE
added new sim files for analysis

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Last sim download from aws was 12/2. This contains today's data (up til 2pm so far)

Will update when more data has come in. 

To run, run `python3 ph1_probe_matcher.py -i ph1_sim_files  -w`

There should not be any "environment undefined" errors. There may be some other warnings/errors due to empty files (I kept those so we can keep track) or missing text/delegation. Nothing should be removed.

### CODE REVIEW

**Comment by kaitlyn-sharo** [comment]
@phile-caci putting this here for now, but I will be pulling more data periodically and adding to this since there are active sim runs now.

**Review by nextcen-dgemoets — COMMENTED** [review]
Well, like you said, no "environment undefined," but lots of other warnings.  I assume these are expected, but I'll include them here for your review just in case:
- `'NoneType' object is not subscriptable`
- `Warn (probeMatcher):     Error getting text response for pid 202411348 adept scenario`
- `Warn (probeMatcher):     Error getting text response for pid 202411330 qol scenario`
- `Warn (probeMatcher):     Error getting text response for pid 202411330 vol scenario`
- `Warn (probeMatcher):     Error getting comparison score (soartech). Perhaps not all probes have been completed in the sim?`  (four times)
- `Warn (probeMatcher):     Could not find match for scene "Scene 1"`
- `Warn (probeMatcher):     Session Alignment Get Request failed`
- `Warn (probeMatcher):     Error getting session id. Maybe alignment hasn't run for file?`
- `Warn (probeMatcher):     Error getting text response for pid 202411330 adept scenario`
- `Warn (probeMatcher):     Error getting comparison score (soartech). Perhaps not all probes have been completed in the sim?`
- `Warn (probeMatcher):     No actions taken`

Either way, nothing was removed.

**Comment by kaitlyn-sharo** [comment]
> Well, like you said, no "environment undefined," but lots of other warnings. I assume these are expected, but I'll include them here for your review just in case:
> 
> * `'NoneType' object is not subscriptable`
> * `Warn (probeMatcher):     Error getting text response for pid 202411348 adept scenario`
> * `Warn (probeMatcher):     Error getting text response for pid 202411330 qol scenario`
> * `Warn (probeMatcher):     Error getting text response for pid 202411330 vol scenario`
> * `Warn (probeMatcher):     Error getting comparison score (soartech). Perhaps not all probes have been completed in the sim?`  (four times)
> * `Warn (probeMatcher):     Could not find match for scene "Scene 1"`
> * `Warn (probeMatcher):     Session Alignment Get Request failed`
> * `Warn (probeMatcher):     Error getting session id. Maybe alignment hasn't run for file?`
> * `Warn (probeMatcher):     Error getting text response for pid 202411330 adept scenario`
> * `Warn (probeMatcher):     Error getting comparison score (soartech). Perhaps not all probes have been completed in the sim?`
> * `Warn (probeMatcher):     No actions taken`
> 
> Either way, nothing was removed.

Those look like what I'm getting!

**Review by nextcen-dgemoets — APPROVED** [review]
The script completed with no "environment undefined" errors. There were many other warnings, but all expected at this point. Nothing was removed.

**Review by brianpippin — APPROVED** [review]
Ran for me, no issues.

**Pull request merged**
