### PR TITLE
Add all ADM history data and yaml scene data to database

### PR DESCRIPTION
**Pull request by brianpippin**
This gets all the metrics evaluation data into the database, however the dashboard DOES NOT look right.  There is a corresponding Dashboard fix to update the labels and to group the datasets by evaluation that will be coming and I am working on.

### CODE REVIEW

**Review by kaitlyn-sharo — COMMENTED** [review]
I can't run this. It keeps saying something about authentication. What are the instructions for running?

**Comment by kaitlyn-sharo** [comment]
> I can't run this. It keeps saying something about authentication. What are the instructions for running?

Actually, I think it was that mongo was pointed to the wrong port now that we've had to change it

**Comment by brianpippin** [comment]
> > I can't run this. It keeps saying something about authentication. What are the instructions for running?
> 
> Actually, I think it was that mongo was pointed to the wrong port now that we've had to change it

Yes we might need to update the port here too if we are changing this permanently.

**Review by kaitlyn-sharo — APPROVED** [review]
Seems to work with the new dashboard page!

**Pull request merged**
