### PR TITLE
created script to get and store comparison scores between text and adms

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Run the deployment script. Two new collections should be created and populated: delegationADMRuns and humanToADMComparison. 

Add comparison scores to database from surveys that have already been completed by matching text scenario session ids to the session ids of adms that appear in the delegation survey for that participant. 
- For ST, send the probe ids to match based on the probes shown in the delegation survey. 
- For Adept, create a new session for the adms that only include the correct probes (IO vs MJ) that are shown in the delegation survey, then send the two session ids
- Create 2 new collections: one for the Adept new adm runs, one to store the comparison results

See matching dashboard ticket to see values in the dashboard

### CODE REVIEW

**Review by dereknop — APPROVED** [review]
Looks good, I'm seeing the expected data populate the two new collections

**Review by phile-caci — APPROVED** [review]
Nice, looks good on my end, scanned through the two new tables everything lookgs good.

**Comment by phile-caci** [comment]
@kaitlyn-sharo , Sry, just a quick thought.. do we need to tag the records with evalNumber for future filtering?

**Comment by kaitlyn-sharo** [comment]
> @kaitlyn-sharo , Sry, just a quick thought.. do we need to tag the records with evalNumber for future filtering?

It can't hurt! Added to all docs

**Comment by phile-caci** [comment]
dropped tables and reran, evalNumber is there, still looks good!

**Review by nextcen-dgemoets — APPROVED** [review]
The data imported and looked good.

**Comment by kaitlyn-sharo** [comment]
For anyone curious, I am waiting to merge this until Brian gets a chance to look at the code just to verify the logic was all correct, since this is an important calculation that will be done in several places soon. We don't want to have the wrong basis for it

**Review by brianpippin — APPROVED** [review]
Everything looked how I understand the calculations to be from Jennifer's instructions, nicely done

**Pull request merged**
