### PR TITLE
Itm 453 adm delegation

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
This ticket, overall, adds adm medics to the database and increases the functionality available in the script from my last PR. Delegation survey scripts and tools are organized in their own folder with its own documentation (see delegation-survey's README). The README should explain most of the code-based changes made.

- Added patient images to upload to the database because otherwise we won't be able to get the right data in mongo in production mode. Set up empty directory for new images for DRE
- Added survey-configs directory with all 4 survey configs. 1 and 2 are as they were, test_config is 2 with no required elements (version 0.0), and 3 is the new survey version with all of the ADM medics we'll be using
- Added templates for adding single and compared medic pages, as well as omnibus and compared-omnibus medic pages
- Added convert_adms_for_delegation script which does exactly what it says
- Added an initialization script in update_survey_config (previously delegation_tool.py) to set up database with 0.0, 1.0, and 2.0 survey versions, as well as images
- Added a script in update_survey_config to configure survey version 3.0 and add it to the database
- Added more details to images added to the database (type of media, patient ids (list, optional), description (optional)) to assist with possible future uses (Derek had mentioned videos possibly) and allowing easier access of images from multiple DMs with the same character with different ids
- Added some new functionality to update_survey_config (clear survey, export to json, import medic from database) and fixed a few minor bugs (i.e. importing a survey imported its version too, but we wanted to overwrite the version with the current version)

To test, first remove all mongo collections that were added in my last PR. Next, delete surveyConfig3x.json. Then, follow the instructions at the bottom of the README. You should see surveyConfig3x repopulate in the survey-configs directory. Check mongo for medics, images, and configs

Note: All delegation-related scripts should be run from within the delegation-survey directory.

Once this is run, test itm-453-adm-delegation in the dashboard

### CODE REVIEW

**Review by dereknop — APPROVED** [review]
Mongo collections updates as described

**Comment by kaitlyn-sharo** [comment]
To test with new names, delete all related database (delegationMedia, delegationConfig, admMedics) and run through the whole process again. This is not fully necessary (only the last two steps of rerunning the adm script and regenerating survey version 3 are necessary), but best to test to make sure images don't get messed up with the new patient names.

**Review by brianpippin — APPROVED** [review]
This looks good to me once we get Jennifer sign off on UI look.

**Comment by brianpippin** [comment]
Derek. Make sure you tag some people to check these changes on Teams and your dashboard ticket so we can get them reviewed. @dereknop

**Pull request merged**
