### PR TITLE
Delegation updates 9-9

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Updated based on feedback from Adept and Soartech. 
- Link to ST feedback: https://nextcentury.atlassian.net/wiki/spaces/ITMC/pages/3382345737/Delegation+Material+Review
- See attached for Adept's feedback. Not all was followed. We kept the vitals for patients to be the initial vitals and let the updates take care of the rest. Additionally, one of their comments did not follow the yaml, and we decided to keep it the way it was to follow the yaml. Most other items were addressed

[observations - review notes 9-9.docx](https://github.com/user-attachments/files/16935528/observations.-.review.notes.9-9.docx)

To run, as usual, enter the delegation_survey directory and run `python3 dre_adms_for_delegation.py`, then run the update script, pressing Enter, then option 3, then y twice

### CODE REVIEW

**Comment by dereknop** [comment]
Grabs mission info for ST pop up in delegation survey

**Comment by nextcen-dgemoets** [comment]
Doesn't the `db_version` need to be updated?  I think we're up to 0.2.1 by now?  Although I'll admit I'm not clear on exactly we're using the version number on this project.  I think we're just supposed to update the version number as necessary.

**Review by phile-caci — APPROVED** [review]
On running ingest before Dereck's commit, I had no warnings, but after Dereck's commit I got these, just noting it in case it matters:
```
(ingest) ple@ple-Virtual-Machine:~/ITM/itm-ingest/delegation_survey$ python3.10 dre_adms_for_delegation.py
Info (ADM Converter):    Successfully added/updated 878 adm medics 
(ingest) ple@ple-Virtual-Machine:~/ITM/itm-ingest/delegation_survey$ python3.10 update_survey_config.py 
Info (Delegation Tool):  Welcome to the Delegation Survey Tool 
Info (Delegation Tool):  To get started, enter the version number you'd like to work on, or press enter for more options: 

Would you like to:
        1. Complete the one time intialization
        2. Setup survey version 3.0
        3. Setup survey version 4.0
3
Warn (Delegation Tool):  This will overwrite all previous delegation survey data in the database. Are you sure you want to do this? (y/n)  
y
Info (Delegation Tool):  Successfully added new page with name 'Participant ID Page' 
Info (Delegation Tool):  Successfully added new page with name 'PID Warning' 
Info (Delegation Tool):  Successfully added new page with name 'Participant ID Page' 
Info (Delegation Tool):  Successfully added new page with name 'Survey Introduction' 
Info (Delegation Tool):  Page successfully imported to survey! 
yWarn (Delegation Tool):         Could not find medic to add to survey. Please check that all details match. Scenario: qol-dre-1-eval, ADM Alignment: qol-human-8022671-SplitLowMulti, ADM Name: ALIGN-ADM-OutlinesBaseline 
Warn (Delegation Tool):  Could not find medic to add to survey. Please check that all details match. Scenario: qol-dre-1-eval, ADM Alignment: qol-human-8022671-SplitLowMulti, ADM Name: ALIGN-ADM-ComparativeRegression-ICL-Template 
Warn (Delegation Tool):  Could not find medic to add to survey. Please check that all details match. Scenario: qol-dre-1-eval, ADM Alignment: qol-human-8022671-SplitLowMulti, ADM Name: TAD-severity-baseline 
Warn (Delegation Tool):  Could not find medic to add to survey. Please check that all details match. Scenario: qol-dre-1-eval, ADM Alignment: qol-human-8022671-SplitLowMulti, ADM Name: TAD-aligned 

Warn (Delegation Tool):  Could not find medic to add to survey. Please check that all details match. Scenario: DryRunEval-IO2-eval, ADM Alignment: ADEPT-DryRun-Ingroup Bias-0.0, ADM Name: ALIGN-ADM-OutlinesBaseline 
Warn (Delegation Tool):  Could not find medic to add to survey. Please check that all details match. Scenario: DryRunEval-IO2-eval, ADM Alignment: ADEPT-DryRun-Ingroup Bias-0.0, ADM Name: ALIGN-ADM-ComparativeRegression-ICL-Template 
Warn (Delegation Tool):  Could not find medic to add to survey. Please check that all details match. Scenario: DryRunEval-MJ5-eval, ADM Alignment: ADEPT-DryRun-Moral judgement-0.8, ADM Name: ALIGN-ADM-ComparativeRegression-ICL-Template 
Info (Delegation Tool):  Page successfully imported to survey! 
Warn (Delegation Tool):  Push all to database? (y/n)  
Info (Delegation Tool):  Survey successfully updated in mongo! 
(ingest) ple@ple-Virtual-Machine:~/ITM/itm-ingest/delegation_survey$ 
```


Spot checked a few items
image

VOL
image

VOL
image

QOL
image

**Comment by phile-caci** [comment]
Thanks @kaitlyn-sharo , that fixed it, no more warnings.

**Review by dereknop — APPROVED** [review]
Looks good (sorry for introducing that bug)

**Review by nextcen-dgemoets — APPROVED** [review]

**Pull request merged**
