### PR TITLE
Itm 762 online pids

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
For consistency in accessing data in other scripts and dashboard pages, it would be nice to make sure the survey PID is stored where it has been stored in previous versions. This retroactively finds all of the survey entries where results.pid exists (new way of storing pid) and makes sure that it also stores in the Participant ID Page (sometimes it does, like for email-only, but sometimes it doesn't, especially for online).

Run this script, then the weekly script will need to be rerun. If it is run before this, it will not be able to find online surveys because it searches for the PID Page. 

Do not run this until testing the dashboard PR

### CODE REVIEW

**Review by brianpippin — APPROVED** [review]
Script ran and I can see online IDs in RQ tables

**Comment by nextcen-dgemoets** [comment]
I got three of these errors:

```
Error getting comparison for scenarios phase1-adept-eval-MJ5 and DryRunEval-MJ4-eval with text session f183bb69-7e5f-440d-883a-cda8dd045be2 and adm session 19e4776a-d9f9-4838-8982-429eec4e4daa {'detail': 'The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.', 'status': 500, 'title': 'Internal Server Error', 'type': 'about:blank'}
```

then got:

```
Traceback (most recent call last):
  File "C:\Users\darren.gemoets_cn\Documents\ITM\git\itm-ingest\ph1_weekly.py", line 18, in <module>
    compare_probes(db, 5)
  File "C:\Users\darren.gemoets_cn\Documents\ITM\git\itm-ingest\scripts\_0_2_8_human_to_adm_comparison.py", line 135, in main
    for target in entry['mostLeastAligned']:
                  ~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'mostLeastAligned'
```

I guess I've got something weird in my database?

**Comment by kaitlyn-sharo** [comment]
> I got three of these errors:
> 
> ```
> Error getting comparison for scenarios phase1-adept-eval-MJ5 and DryRunEval-MJ4-eval with text session f183bb69-7e5f-440d-883a-cda8dd045be2 and adm session 19e4776a-d9f9-4838-8982-429eec4e4daa {'detail': 'The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.', 'status': 500, 'title': 'Internal Server Error', 'type': 'about:blank'}
> ```
> 
> then got:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\darren.gemoets_cn\Documents\ITM\git\itm-ingest\ph1_weekly.py", line 18, in <module>
>     compare_probes(db, 5)
>   File "C:\Users\darren.gemoets_cn\Documents\ITM\git\itm-ingest\scripts\_0_2_8_human_to_adm_comparison.py", line 135, in main
>     for target in entry['mostLeastAligned']:
>                   ~~~~~^^^^^^^^^^^^^^^^^^^^
> KeyError: 'mostLeastAligned'
> ```
> 
> I guess I've got something weird in my database?

Probably missing some surveys

**Review by nextcen-dgemoets — APPROVED** [review]
I re-ran this with Monday night's DB backup.  It got a lot farther, including 83 "No survey found for <PID>" messages and 9 "No matching adm found for scenario <scenario_id>" messages.  But eventually I got the same error/crash as before.  If feel like there's some edge case that isn't being accounted for, presumably in `_0_2_8_human_to_adm_comparison.py` where the crash occurred.

I generally prefer to be able to complete the instructions in the PR before approving, but it's clear that the problem is not with this script.

**Comment by kaitlyn-sharo** [comment]
> I re-ran this with Monday night's DB backup. It got a lot farther, including 83 "No survey found for " messages and 9 "No matching adm found for scenario <scenario_id>" messages. But eventually I got the same error/crash as before. If feel like there's some edge case that isn't being accounted for, presumably in `_0_2_8_human_to_adm_comparison.py` where the crash occurred.
> 
> I generally prefer to be able to complete the instructions in the PR before approving, but it's clear that the problem is not with this script.

I am still not seeing this, using last night's backup. I do get lots of "no survey found", which is expected because of the online participants who did not complete the survey and the in-person participants who said it was "too boring", but everything runs fine. However, since you posted the line it's erroring on, I will throw in a quick if statement to just continue if mostLeastAligned does not exist

**Comment by kaitlyn-sharo** [comment]
Darren's problems were due to local data without mostLeastAligned (because of CORS issues). However, I did put in fixes to ignore those errors and continue through the script. Everything runs through for him now

**Pull request merged**
